services:
  aberit_mysql:
    image: mysql:latest
    container_name: ${DOCKER_PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: gF*W2Ruy509OaYL2
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DOCKER_IP}:${DOCKER_PORT_DB}:${DB_PORT}"
    volumes:
      - ./mysql_data:/var/lib/mysql

  aberit_php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ${DOCKER_PROJECT_NAME}_php
    depends_on:
      - aberit_mysql
    volumes:
      - ../../:/var/www/
      - ./php/etc/php-development.ini:/usr/local/etc/php/php.ini
      # - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"

  aberit_nginx:
    image: nginx:1-alpine
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    depends_on:
      - aberit_php
    ports:
      - "${DOCKER_IP}:${DOCKER_PORT_HTTP}:80"
      - "${DOCKER_IP}:18150:443"
    volumes:
      - ../../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
